@endpoint = https://7z1getygu6.execute-api.us-west-1.amazonaws.com/prod

GET {{endpoint}}/hello
###

GET {{endpoint}}/spaces?spaceId=26297328-0445-4768-b693-575659b2577b
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
  "location": "SF",
  "name": "Best location"
}
###